# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Fun and Games Blog
title_separator: "|"
author: HighTowerr
name: OO
email: olayinkaola89@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Passionate about product. Python enthusiast eager to build things.
baseurl: "/fun-and-games" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: y1nk
github_username:  hightowerr

## Post dates
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      share: true
      comments: true

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-YQ4WFXQ3FG" # Replace this with your ID, or delete
    anonymize_ip         : true

## author
author:
  name: "Yink"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Python & R for data enthusiast working in product" # Note: Markdown is allowed
  location: "Somewhere"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/y1nk_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hightowerr"
    - label: "LinkedIn"
      icon: "fab fa-linkedin-square"
      url: "https://www.linkedin.com/in/yinkola/"

## Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hightowerr"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/yinkola/"

# Build settings
#theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon" # "air", "aqua", "default", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-gist

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
